#!/usr/bin/env bun
// Installs `swarmail guard` into a repository's pre-commit and pre-push hook chains (hooks.d/<hook>/50-swarmail-guard)
// Usage: bun scripts/install-guard.ts [--dry-run] [repo...]   (default: this repository)
// The hooks run ~/.local/bin/swarmail (scripts/enable.sh builds it) and pass when it is missing.
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { binaryPath } from "../src/paths.ts";
import { dirname, join, resolve } from "node:path";

export const guardMarker = "Generated by the Swarmail guard installer (scripts/install-guard.ts)";
const HOOKS = ["pre-commit", "pre-push"] as const;

const commonDir = (dir: string) =>
  execFileSync("git", ["rev-parse", "--path-format=absolute", "--git-common-dir"], {
    cwd: dir,
    encoding: "utf8",
  }).trim();

export const guardHook = (bin: string, hook: string) => `#!/bin/sh
# ${guardMarker}
[ -x "${bin}" ] || exit 0
exec "${bin}" guard ${hook}
`;

export function installSwarmailGuard(repo: string, { bin = binaryPath(), dryRun = false } = {}) {
  const hooksDir = join(commonDir(repo), "hooks");
  const changed: string[] = [];
  for (const hook of HOOKS) {
    // Only the chain runner dispatches hooks.d; a plain hook there would never run the guard.
    if (!existsSync(join(hooksDir, hook))) {
      throw new Error(`${hooksDir}/${hook} is missing: no hook chain runs hooks.d/${hook}`);
    }
    const path = join(hooksDir, "hooks.d", hook, "50-swarmail-guard");
    const content = guardHook(bin, hook);
    const current = existsSync(path) ? readFileSync(path, "utf8") : null;
    if (current !== content) {
      changed.push(path);
    }
    if (dryRun) {
      continue;
    }
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, { mode: 0o755 });
    chmodSync(path, 0o755);
  }
  return changed;
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry-run");
  const repos = args.filter((a) => a !== "--dry-run");
  for (const repo of repos.length ? repos : [dirname(commonDir(import.meta.dir))]) {
    const changed = installSwarmailGuard(resolve(repo), { dryRun });
    console.log(
      `${repo}: ${changed.length ? (dryRun ? "would change " : "changed ") + changed.join(", ") : "current"}`,
    );
  }
}
